// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PictureGuessing.Models;

namespace PictureGuessing.Migrations
{
    [DbContext(typeof(PictureGuessingDbContext))]
    [Migration("20191219193520_DifficultyScale to Key")]
    partial class DifficultyScaletoKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PictureGuessing.Models.Difficulty", b =>
                {
                    b.Property<float>("DifficultyScale")
                        .HasColumnType("real");

                    b.Property<int>("cols")
                        .HasColumnType("int");

                    b.Property<float>("revealDelay")
                        .HasColumnType("real");

                    b.Property<int>("rows")
                        .HasColumnType("int");

                    b.HasKey("DifficultyScale");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("PictureGuessing.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("DifficultyScale")
                        .HasColumnType("real");

                    b.Property<bool>("isFinished")
                        .HasColumnType("bit");

                    b.Property<Guid>("pictureID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyScale");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("PictureGuessing.Models.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnswerLength")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("PictureGuessing.Models.Game", b =>
                {
                    b.HasOne("PictureGuessing.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyScale");
                });
#pragma warning restore 612, 618
        }
    }
}
